### ISSUE TITLE
Freeze and bootloop

### ISSUE THREAD

**Issue by javarhol** [dmlls/InfiniTime#1]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Selecting watchface and pressing back button freezes pinetime

### What should happen instead?

Selecting watchface and pressing back button returns to home screen / watch face

### Reproduction steps

I installed the firmware and the new watchface doesn't seem to work. When I select the watchface and press the back button, the watch returns to the full settings menu, then the press the button again and it returns to the quick settings menu and freezes. 
Watch then reboots to previous firmware or need to do a hard reset. 

Terminal watchface works fine.

### More details?

I downloaded the firmware twice on my android 12.0 phone (Pixel 6) and it occurred both times. Was able to also replicate it after installing the firmware via Gadgetbridge or nRF connect. 

### Version

1.8.0

### Companion app

Gadgetbridge, nRF connect

**Comment by NeroBurner** [comment]
can confirm with compiling firmware myself and flashing over gadgetbridge, when attempting to open the watchface the watch freezes and reboots

**Comment by carbonatedcaffeine** [comment]
I can also confirm this issue as well.

**Comment by NeroBurner** [comment]
To try to get a better picture on what is going on I want to share two funky experiences with regard to the Infineat watchface:

I had some weird issues with the settings overlay to have the on/off status switched (the nice logo on the left side was shown when overlay setting said OFF). And the toggle only worked once, to make it work again I had to restart the simulator. After I removed the `settings.dat` file the Infineat watchface settings worked like a charm (unfortunately I typed `rm settings.dat` and had no backup, which would have been nice to try to reproduce the bug :see_no_evil: )

Later I had a brightness related bug while working in the Simulator with the new Infineat Watchface like https://github.com/InfiniTimeOrg/InfiniTime/pull/1024#issuecomment-1064172407 mentioned. The brightness was always at off or at lowest. Fortunately in the simulator I have the possibility to hit the `l` or `L` key to increase/decrease the brightness

**Comment by dmlls** [comment]
First off, I apologize for the issues you might have experienced. I haven't had any of these problems on any of both my 2 PineTimes, but it is also true that I installed the firmware via `openocd` with the pogo pin.

The watchface introduced a couple of new settings that are stored in the internal settings file. Only thing I can imagine is that this file is getting corrupted somehow when upgrading from 1.8.0. Something interesting to try is downgrading first to 1.7.1 and then installing Infineat again, and checking whether these issues are still there.

I already added a warning in the release so everyone is aware of these possible issues before attempting any install. I wouldn't like to see any bricked Pinetimes ;)

**Comment by NeroBurner** [comment]
@dmlls have you tried bumping the settings version? I don't know when this is needed, but maybe it's related

https://github.com/InfiniTimeOrg/InfiniTime/blob/c549953b3855e7661c66abf796f8871321103440/src/components/settings/Settings.h#L248

**Comment by dmlls** [comment]
@NeroBurner that's a good point, I already bumped it and also rebased upstream `develop`. Let see if that fixes it.

**Comment by dmlls** [comment]
@javarhol @EnderNightLord-ChromeBook @NeroBurner @ytsejam1138 @joseph58tech I created a [new release](https://github.com/dmlls/InfiniTime/releases/tag/1.8.0-2-infineat). If you guys could test whether the problems still persist, that would be very helpful!

**Comment by joseph58tech** [comment]
> @javarhol @EnderNightLord-ChromeBook @NeroBurner @ytsejam1138 @joseph58tech I created a [new release](https://github.com/dmlls/InfiniTime/releases/tag/1.8.0-2-infineat). If you guys could test whether the problems still persist, that would be very helpful!

The new release seems to have fixed everything

**Comment by ytsejam1138** [comment]
Confirmed, freeze is also fixed for me. Works as intended now.

**Comment by javarhol** [comment]
We're in business!
