### ISSUE TITLE
Rebase and squash PR to latest develop because of font changes

### ISSUE THREAD

**Issue by NeroBurner** [dmlls/InfiniTime#2]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

rebase the PR and squash the PR down to one commit to get newest fixes

### Description

upstream develop branch fixed a sneaky memory corruption in the chimes options f47b04ffd0ee401381f18cfedd716d492b4c7db8

Furthermore the font files were updated 204ad7ca2a8bf30caee7bc9b7395001c0d720b10 as well making merging current `develop` branch into `infineat-pr`  branch a hassle (as well as rebasing)

As third, after rebasing this branch can be built with `InfiniSim` and the PR will be built against InfiniSim thanks to 4c92ed410f89ba398b8762384bae395ff1d344c9

So I suggest rebasing and squashing the `infineat-pr` down to one commit

**Comment by NeroBurner** [comment]
ping @dmlls

**Comment by NeroBurner** [comment]
for example I made some screenshots using InfiniSim (just pressing `i`)
![InfiniSim_2022-03-09_203812](https://user-images.githubusercontent.com/9076163/157553308-9002a5d5-69c2-474c-aa33-b8460d900f09.png) ![InfiniSim_2022-03-09_203821](https://user-images.githubusercontent.com/9076163/157553310-865bf3c3-f409-49c2-a360-e5fa106fa3c4.png) ![InfiniSim_2022-03-09_203827](https://user-images.githubusercontent.com/9076163/157553312-f732713c-2fb0-4c5c-aae1-45c6b00401fc.png) ![InfiniSim_2022-03-09_203853](https://user-images.githubusercontent.com/9076163/157553314-b67e37d0-39ed-47a6-8a53-6a99604d342b.png)

**Comment by dmlls** [comment]
@NeroBurner thanks for your feedback and nice to see the watchface on InfiniSim :)

I'll rebase upstream `develop` as you suggest. Only thing, by squashing you mean squashing the latest upstream changes into the last commit in `infineat-pr` (https://github.com/dmlls/InfiniTime/commit/c549953b3855e7661c66abf796f8871321103440 ` All ready for PR`) right?

**Comment by NeroBurner** [comment]
hmmm I think squashing into the `All ready for PR` would be hard, as it is the latest commit

just squash all into your first commit and update the commit description to include a description of what the intent of your commit is. It's not important which commit you squash into. The final commit is the thing that is important :)

**Comment by dmlls** [comment]
Upstream `develop` rebased 👍🏻

I will keep the `infineat-pr` updated with the changes happening upstream.
