### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [dmlls/InfiniTime#4]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

I go to flash and my watch won't flash ur

### Reproduction steps

What should I do

### Version

the newest

**Comment by ghost** [comment]
@dmlls

**Comment by dmlls** [comment]
Hi @T-campbell572, I must have missed the notification for the issue.

Can you please provide more details on how you are performing the install? For example, did you try to install it from Android? If so, which app did you use, Gadgetbridge, nRF Connect?

**Comment by ghost** [comment]
> Hi @T-campbell572, I must have missed the notification for the issue.
> 
> Can you please provide more details on how you are performing the install? For example, did you try to install it from Android? If so, which app did you use, Gadgetbridge, nRF Connect?


I used nRF connect but I narrowed it down to the newest version I installed a older verison and it worked

**Comment by ghost** [comment]
Also I have made this issue aware to pine64 in the pine64 discord

**Comment by dmlls** [comment]
So if I understood correctly, the problem was the nRF Connect version? I.e., latest version not being able to install the firmware correctly?

**Comment by ghost** [comment]
> So if I understood correctly, the problem was the nRF Connect version? I.e., latest version not being able to install the firmware correctly?

Yeah and btw Iove your watch face

**Comment by dmlls** [comment]
Thanks! 🙂 And glad the issue is solved.
