### ISSUE TITLE
Boot looping after not verifying and restarting

### ISSUE THREAD

**Issue by joseph58tech** [dmlls/InfiniTime#5]
My watch died and when I went to plug it in and turn it back on (I forgot to verify the OS) it started boot looping, I also can't access the recovery screen as the device is boot looping extremely fast.

**Comment by joseph58tech** [comment]
https://photos.app.goo.gl/4PNepJseRNYvKSY68
This is a video of the boot looping process

**Comment by joseph58tech** [comment]
Updated video https://photos.app.goo.gl/ENL9eHuVjW7mHGaJ6

**Comment by dmlls** [comment]
Hi @joseph58tech, I'm sorry I totally missed this issue! (apparently I only had notifications enabled for mentions).

Did you manage to solve it by now? If not, have you tried waiting for one or two weeks for complete discharge and then plugging it back in?

**Comment by joseph58tech** [comment]
Yeah, it didn't work so I bought a new watch. But I may have not waited long enough for the watch to completely discharge.

**Comment by dmlls** [comment]
@joseph58tech ups 😬 If you still have the old watch you can always give it a try, maybe there's luck...

**Comment by joseph58tech** [comment]
Yeah, I do still have the old watch, so I'll probably wait until next Saturday to power it on again (next Saturday would be 2 weeks since last attempt).
